# Change these first
owner: j-stuff # Your GitHub organization or username, where this repository lives
repo: status-monitor # The name of this repository

sites:
  - name: Homepage
    url: https://j-stuff.net/
    maxResponseTime: 5000

  - name: CDN
    url: https://cdn.j-stuff.net/
    maxResponseTime: 5000
    
  - name: Remote 1
    url: $REMOTE_1_STATUS_URL
    maxResponseTime: 5000

  - name: KaspBot
    url: $KASPBOT_CHECK_URL
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.j-stuff.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: j-stuff.net | Uptime
  introTitle: "j-stuff.net sitewide system status"
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
user-agent: j-stuff_(jstuff[email_symbol]j-stuff.net)
